### ISSUE TITLE
Ctrl+Shift+Right Shortcut Does Not Work

### ISSUE THREAD

**Issue by AhmetRufai** [maximehamm/tzatziki#1]
Hi,
The plugin you have developed is really useful. This plugin allowed us to do many things that we thought to do but could not do in using Cucumber Outline. Thanks for your effort. You did a really good job.

I ran into a problem like this. It didn't work when I used the Ctrl+Shift+Right shortcut to replace a column in the Cucumber Outline table with another column to the right of the column. Other functions and shortcuts are working correctly. Can you help with this?

Exception log in stacktrace.txt and induced.txt file:
```
java.lang.IllegalArgumentException: No enum constant io.nimbly.tzatziki.actions.Direction.RİGHT
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at io.nimbly.tzatziki.actions.Direction.valueOf(TzTableShiftAction.kt)
	at io.nimbly.tzatziki.actions.TableShiftAction.getDirection(TzTableShiftAction.kt:52)
	at io.nimbly.tzatziki.actions.TableShiftAction.actionPerformed(TzTableShiftAction.kt:45)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:615)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:522)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:892)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Thanks,
Ahmet

**Comment by maximehamm** [comment]
There is a dot above the "I" i RIGHT ! It comes from you're locale language I think ! I will fix that very soon !

**Comment by maximehamm** [comment]
A new version 2.4.1 should be available friday resolving this issue :)

**Comment by AhmetRufai** [comment]
Hi,
Yes, the capitalization of the letter "i" in the local language is used as "İ". Probably this is the reason. Thank you for the quick solution :)
