### ISSUE TITLE
IndexNotReadyException from KotlinTzatzikiExtensionPoint.kt

### ISSUE THREAD

**Issue by iromeo** [maximehamm/tzatziki#10]
```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to JetBrains Team / Roman Chernyatchik
You have a perpetual fallback license for this version.
Subscription is active until March 30, 2023.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2448M
Cores: 16
Registry: analyze.exceptions.on.the.fly=true, ide.windowSystem.autoShowProcessPopup=true, idea.profiler.jvm.dtrace=true
Non-Bundled Plugins: IdeaVIM (0.69), org.jetbrains.idea.grammar (2021.1.1), Jetbrains TeamCity Plugin (2021.1.98828), Pythonid (212.4746.96), io.nimbly.tzatziki (9.0.0)
Kotlin: 212-1.5.10-release-IJ4746.92
```

```
java.lang.RuntimeException: com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at git4idea.branch.GitBranchOperation.notifyBranchHasChanged(GitBranchOperation.java:283)
	at git4idea.branch.GitCheckoutOperation.execute(GitCheckoutOperation.java:156)
	at git4idea.branch.GitBranchWorker.checkout(GitBranchWorker.java:116)
	at org.jetbrains.plugins.github.pullrequest.action.GHPRCreateBranchAction$checkoutBranch$1.run(GHPRCreateBranchAction.kt:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:821)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:773)
	at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:429)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:68)
	at com.intellij.psi.stubs.StubIndexImpl.getAllKeys(StubIndexImpl.java:417)
	at com.intellij.psi.stubs.AbstractStubIndex.getAllKeys(AbstractStubIndex.java:14)
	at org.jetbrains.kotlin.idea.stubindex.SubpackagesIndexService$cachedValue$1.compute(SubpackagesIndexService.kt:21)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.idea.stubindex.SubpackagesIndexService$Companion.getInstance(SubpackagesIndexService.kt:82)
	at org.jetbrains.kotlin.idea.stubindex.PackageIndexUtil.packageExists(PackageIndexUtil.kt:40)
	at org.jetbrains.kotlin.idea.caches.PerModulePackageCacheService.packageExists(PerModulePackageCacheService.kt:389)
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.stubBasedPackageExists(PluginDeclarationProviderFactory.kt:54)
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.packageExists(PluginDeclarationProviderFactory.kt:49)
	at org.jetbrains.kotlin.resolve.lazy.declarations.AbstractDeclarationProviderFactory.getPackageMemberDeclarationProvider(AbstractDeclarationProviderFactory.java:41)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getPackageFragment(ResolveSession.java:252)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getPackageFragmentOrDiagnoseFailure(ResolveSession.java:267)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile(FileScopeFactory.kt:63)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile$default(FileScopeFactory.kt:61)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:48)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:46)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileScopes(FileScopeProvider.kt:53)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProvider$DefaultImpls.getFileResolutionScope(FileScopeProvider.kt:30)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileResolutionScope(FileScopeProvider.kt:40)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.createAnnotations(ResolveSession.java:237)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.lambda$new$0(ResolveSession.java:226)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getFileAnnotations(ResolveSession.java:373)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.ensureFileAnnotationsResolved(ResolveElementCache.kt:307)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.resolveToElements(ResolveElementCache.kt:274)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$1.invoke(ModuleResolutionFacadeImpl.kt:54)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$1.invoke(ModuleResolutionFacadeImpl.kt:28)
	at com.intellij.openapi.progress.impl.CancellationCheck.withCancellationCheck(CancellationCheck.kt:59)
	at com.intellij.openapi.progress.impl.CancellationCheck$Companion.runWithCancellationCheck(CancellationCheck.kt:105)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runWithCancellationCheck(ApplicationUtils.kt:45)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:53)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.analyze(extendedResolutionApi.kt:94)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.resolveToDescriptorIfAny(extendedResolutionApi.kt:36)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptorIfAny(resolutionApi.kt:58)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport.resolveToDescriptor(IDELightClassGenerationSupport.kt:146)
	at org.jetbrains.kotlin.asJava.classes.UltraLightUtilsKt.resolve(ultraLightUtils.kt:156)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternal(ultraLightMembersCreator.kt:390)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternalNonPublishedApi(ultraLightMembersCreator.kt:380)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.computeMethodName(ultraLightMembersCreator.kt:367)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod(ultraLightMembersCreator.kt:174)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod$default(ultraLightMembersCreator.kt:163)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods(ultraLightMembersCreator.kt:119)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods$default(ultraLightMembersCreator.kt:107)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.ownMethods(ultraLightClass.kt:274)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass._ownMethods$lambda-7(ultraLightClass.kt:334)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.getOwnMethods(ultraLightClass.kt:474)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getAllMethods(KotlinClassInnerStuffCache.kt:105)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.access$getAllMethods(KotlinClassInnerStuffCache.kt:22)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$_getMethods$2.invoke(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$_getMethods$2.invoke(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1$holder$1.invoke$lambda-0(LightClassesLazyCreator.kt:21)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.computeValue(LightClassesLazyCreator.kt:26)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.getValue(LightClassesLazyCreator.kt:50)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.get_getMethods(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getMethods(KotlinClassInnerStuffCache.kt:49)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getMethods(KtLightClassBase.kt:43)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$1.invoke(LightClassUtil.kt:136)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$1.invoke(LightClassUtil.kt:136)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassMethods(LightClassUtil.kt:124)
	at org.jetbrains.kotlin.asJava.LightClassUtilsKt.toLightMethods(lightClassUtils.kt:84)
	at org.jetbrains.kotlin.idea.asJava.LightClassProviderImpl.toLightMethods(LightClassProviderImpl.kt:30)
	at org.jetbrains.kotlin.idea.asJava.LightClassProvider$Companion.providedToLightMethods(LightClassProvider.kt:59)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindMemberUsagesHandler$MySearcher.buildTaskList(KotlinFindMemberUsagesHandler.kt:281)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler$searchReferences$2.invoke(KotlinFindUsagesHandler.kt:79)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler$searchReferences$2.invoke(KotlinFindUsagesHandler.kt:24)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadActionInSmartMode(ApplicationUtils.kt:66)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler.searchReferences(KotlinFindUsagesHandler.kt:79)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler.processElementUsages(KotlinFindUsagesHandler.kt:69)
	at io.nimbly.tzatziki.KotlinTzatzikiExtensionPoint$initBreakpointListener$1.invoke(KotlinTzatzikiExtensionPoint.kt:68)
	at io.nimbly.tzatziki.KotlinTzatzikiExtensionPoint$initBreakpointListener$2.breakpointRemoved(KotlinTzatzikiExtensionPoint.kt:93)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy260.breakpointRemoved(Unknown Source)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.lambda$doRemoveBreakpointImpl$5(XBreakpointManagerImpl.java:290)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.sendBreakpointEvent(XBreakpointManagerImpl.java:300)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.doRemoveBreakpointImpl(XBreakpointManagerImpl.java:290)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.doRemoveBreakpoint(XBreakpointManagerImpl.java:270)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.removeBreakpoint(XBreakpointManagerImpl.java:253)
	at com.intellij.tasks.context.XDebuggerBreakpointsContextProvider.lambda$clearContext$0(XDebuggerBreakpointsContextProvider.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.tasks.context.XDebuggerBreakpointsContextProvider.clearContext(XDebuggerBreakpointsContextProvider.java:60)
	at com.intellij.tasks.context.WorkingContextManager.clearContext(WorkingContextManager.java:96)
	at com.intellij.tasks.context.BranchContextTracker.switchContext(BranchContextTracker.java:62)
	at com.intellij.tasks.context.BranchContextTracker.lambda$branchHasChanged$1(BranchContextTracker.java:57)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:45)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:69)
	at com.intellij.tasks.context.BranchContextTracker.branchHasChanged(BranchContextTracker.java:57)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy292.branchHasChanged(Unknown Source)
	at git4idea.branch.GitBranchOperation.lambda$notifyBranchHasChanged$3(GitBranchOperation.java:285)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:451)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by maximehamm** [comment]
Hello Romane
Should be fixed in next release !
Maxime

**Comment by iromeo** [comment]
@maximehamm Also in `9.0.1` ?

**Comment by maximehamm** [comment]
yes !
