### ISSUE TITLE
Slow operations are prohibited on EDT

### ISSUE THREAD

**Issue by theotherp** [maximehamm/tzatziki#19]
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:110)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:754)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:501)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:305)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:30)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:84)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:110)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:51)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:91)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:69)
	at com.intellij.psi.util.ClassUtil.findPsiClass(ClassUtil.java:182)
	at com.intellij.execution.testframework.JavaTestLocator.collectMethodNavigatables(JavaTestLocator.java:144)
	at com.intellij.execution.testframework.JavaTestLocator.collectMethodNavigatables(JavaTestLocator.java:125)
	at com.intellij.execution.testframework.JavaTestLocator.getLocation(JavaTestLocator.java:66)
	at com.intellij.execution.testframework.JavaTestLocator.getLocation(JavaTestLocator.java:79)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$CombinedTestLocator.getLocation(SMTestRunnerConnectionUtil.java:247)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.lambda$computeLocation$2(SMTestProxy.java:302)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:361)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.computeLocation(SMTestProxy.java:301)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.lambda$getLocation$0(SMTestProxy.java:284)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.execution.testframework.sm.runner.SMTestProxy.getLocation(SMTestProxy.java:288)
	at io.nimbly.tzatziki.util.TestProxyUtilsKt.findElement(TestProxyUtils.kt:48)
	at io.nimbly.tzatziki.testdiscovery.TzTestStatusListener.findTestSteps(TzTestStatusListener.kt:61)
	at io.nimbly.tzatziki.testdiscovery.TzTestStatusListener.testSuiteFinished(TzTestStatusListener.kt:49)
	at com.intellij.execution.testframework.TestStatusListener.notifySuiteFinished(TestStatusListener.java:19)
	at com.intellij.execution.testframework.TestsUIUtil.notifyByBalloon(TestsUIUtil.java:106)
	at com.intellij.execution.testframework.sm.runner.ui.SMTestRunnerResultsForm.lambda$onTestingFinished$1(SMTestRunnerResultsForm.java:289)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Latest plugin version with IntelliJ 2021.2.2

**Comment by maximehamm** [comment]
Fixed in next release.
Thank you
