### ISSUE TITLE
Cucumber 9.1.0 + IDEA 2021.3: IndexNotReadyException from `io.nimbly.tzatziki.psi.GherkinPsiUtilsKt.findUsages`

### ISSUE THREAD

**Issue by iromeo** [maximehamm/tzatziki#25]
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:852)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:804)
	at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:442)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:68)
	at com.intellij.psi.stubs.StubIndexImpl.getAllKeys(StubIndexImpl.java:430)
	at com.intellij.psi.stubs.AbstractStubIndex.getAllKeys(AbstractStubIndex.java:14)
	at org.jetbrains.kotlin.idea.stubindex.SubpackagesIndexService$cachedValue$1.compute(SubpackagesIndexService.kt:21)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.idea.stubindex.SubpackagesIndexService$Companion.getInstance(SubpackagesIndexService.kt:82)
	at org.jetbrains.kotlin.idea.stubindex.PackageIndexUtil.packageExists(PackageIndexUtil.kt:40)
	at org.jetbrains.kotlin.idea.caches.PerModulePackageCacheService.packageExists(PerModulePackageCacheService.kt:389)
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.stubBasedPackageExists(PluginDeclarationProviderFactory.kt:54)
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.packageExists(PluginDeclarationProviderFactory.kt:49)
	at org.jetbrains.kotlin.resolve.lazy.declarations.AbstractDeclarationProviderFactory.getPackageMemberDeclarationProvider(AbstractDeclarationProviderFactory.java:41)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getPackageFragment(ResolveSession.java:252)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getPackageFragmentOrDiagnoseFailure(ResolveSession.java:267)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile(FileScopeFactory.kt:63)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile$default(FileScopeFactory.kt:61)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:48)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:46)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileScopes(FileScopeProvider.kt:53)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProvider$DefaultImpls.getFileResolutionScope(FileScopeProvider.kt:30)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileResolutionScope(FileScopeProvider.kt:40)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.createAnnotations(ResolveSession.java:237)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.lambda$new$0(ResolveSession.java:226)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getFileAnnotations(ResolveSession.java:373)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.ensureFileAnnotationsResolved(ResolveElementCache.kt:341)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.resolveToElement(ResolveElementCache.kt:275)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$1.invoke(ModuleResolutionFacadeImpl.kt:48)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$1.invoke(ModuleResolutionFacadeImpl.kt:28)
	at com.intellij.openapi.progress.impl.CancellationCheck.withCancellationCheck(CancellationCheck.kt:59)
	at com.intellij.openapi.progress.impl.CancellationCheck$Companion.runWithCancellationCheck(CancellationCheck.kt:105)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runWithCancellationCheck(ApplicationUtils.kt:69)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:47)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:44)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.analyze(extendedResolutionApi.kt:102)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.safeAnalyze(extendedResolutionApi.kt:93)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.resolveToDescriptorIfAny(extendedResolutionApi.kt:37)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptorIfAny(resolutionApi.kt:60)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport.resolveToDescriptor(IDELightClassGenerationSupport.kt:144)
	at org.jetbrains.kotlin.asJava.classes.UltraLightUtilsKt.resolve(ultraLightUtils.kt:156)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternal(ultraLightMembersCreator.kt:390)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternalNonPublishedApi(ultraLightMembersCreator.kt:380)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.computeMethodName(ultraLightMembersCreator.kt:367)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod(ultraLightMembersCreator.kt:174)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod$default(ultraLightMembersCreator.kt:163)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods(ultraLightMembersCreator.kt:119)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods$default(ultraLightMembersCreator.kt:107)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.ownMethods(ultraLightClass.kt:274)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass._ownMethods$lambda-7(ultraLightClass.kt:334)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.getOwnMethods(ultraLightClass.kt:474)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getAllMethods(KotlinClassInnerStuffCache.kt:105)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.access$getAllMethods(KotlinClassInnerStuffCache.kt:22)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$_getMethods$2.invoke(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$_getMethods$2.invoke(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1$holder$1.invoke$lambda-0(LightClassesLazyCreator.kt:21)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.computeValue(LightClassesLazyCreator.kt:26)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.getValue(LightClassesLazyCreator.kt:50)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.get_getMethods(KotlinClassInnerStuffCache.kt:46)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getMethods(KotlinClassInnerStuffCache.kt:49)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getMethods(KtLightClassBase.kt:43)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$1.invoke(LightClassUtil.kt:136)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$1.invoke(LightClassUtil.kt:136)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassMethods(LightClassUtil.kt:124)
	at org.jetbrains.kotlin.asJava.LightClassUtilsKt.toLightMethods(lightClassUtils.kt:84)
	at org.jetbrains.kotlin.idea.asJava.LightClassProviderImpl.toLightMethods(LightClassProviderImpl.kt:30)
	at org.jetbrains.kotlin.idea.asJava.LightClassProvider$Companion.providedToLightMethods(LightClassProvider.kt:59)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindMemberUsagesHandler$MySearcher.buildTaskList(KotlinFindMemberUsagesHandler.kt:283)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler$searchReferences$2.invoke(KotlinFindUsagesHandler.kt:79)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler$searchReferences$2.invoke(KotlinFindUsagesHandler.kt:24)
	at org.jetbrains.kotlin.idea.util.DumbUtilsKt.runReadActionInSmartMode(dumbUtils.kt:10)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler.searchReferences(KotlinFindUsagesHandler.kt:79)
	at org.jetbrains.kotlin.idea.findUsages.handlers.KotlinFindUsagesHandler.processElementUsages(KotlinFindUsagesHandler.kt:69)
	at io.nimbly.tzatziki.psi.GherkinPsiUtilsKt.findUsages(GherkinPsiUtils.kt:128)
	at io.nimbly.tzatziki.KotlinTzatzikiExtensionPoint$initBreakpointListener$1$1.run(KotlinTzatzikiExtensionPoint.kt:66)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:144)
	at io.nimbly.tzatziki.KotlinTzatzikiExtensionPoint$initBreakpointListener$1.invoke(KotlinTzatzikiExtensionPoint.kt:64)
	at io.nimbly.tzatziki.KotlinTzatzikiExtensionPoint$initBreakpointListener$2.breakpointChanged(KotlinTzatzikiExtensionPoint.kt:86)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy300.breakpointChanged(Unknown Source)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.lambda$fireBreakpointChanged$3(XBreakpointManagerImpl.java:241)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.sendBreakpointEvent(XBreakpointManagerImpl.java:302)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.fireBreakpointChanged(XBreakpointManagerImpl.java:241)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointBase.fireBreakpointChanged(XBreakpointBase.java:104)
	at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointImpl.setLine(XLineBreakpointImpl.java:318)
	at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointImpl.updatePosition(XLineBreakpointImpl.java:297)
	at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointManager.updateBreakpoints(XLineBreakpointManager.java:160)
	at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointManager$MyDocumentListener$1.run(XLineBreakpointManager.java:220)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:147)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2196)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:241)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:374)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by maximehamm** [comment]
Hello Roman
This should be fixed in new release 9.2.0
Let me know !
Maxime
