### ISSUE TITLE
Error when opening Intellij with Version 17.0.0 of cucumber+ Plugin.

### ISSUE THREAD

**Issue by julalorena** [maximehamm/tzatziki#73]
I have Version 17.0.0 of the cucumber+ Plugin.
I am unable to set Breakpoints and I am getting this error:

![image](https://github.com/maximehamm/tzatziki/assets/165150330/965049e1-d58d-41e9-a561-05737e911ddf)

**Comment by maximehamm** [comment]
Please tell me which Jetbrain product you're using + version
Is the "Kotlin" plugin installed ?

**Comment by binodluitel** [comment]
I am having the same issue with 17.0.15 version.
![Screenshot 2024-03-28 at 4 18 28 PM](https://github.com/maximehamm/tzatziki/assets/592437/94d2ca47-2976-4ebc-930b-87584d887463)

I am using JetBrains Goland

```
GoLand 2023.3.6
Build #GO-233.15026.17, built on March 21, 2024
Licensed to StackPath / Binod Luitel
Subscription is active until June 19, 2024.
Runtime version: 17.0.10+1-b1087.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  bundled-goland-help (233.15026.17)
  com.intellij.ideolog (222.3.2.0)
  com.intellij.properties (233.11799.172)
  com.intellij.mermaid (0.0.20+IJ.232)
  gherkin (233.11799.165)
  io.nimbly.tzatziki (17.0.15)
  com.jetbrains.space (233.15026.16)
  com.intellij.grazie.pro (0.3.294)
  PlantUML integration (7.7.1-IJ2023.2)
  com.github.bufbuild.intellij (0.3.1)
  com.github.copilot (1.5.1.5285)
  mobi.hsz.idea.gitignore (4.5.2)
  intellij.prettierJS (233.13135.104)
```

this is the error 

```
java.lang.NoClassDefFoundError: org/jetbrains/plugins/cucumber/java/run/CucumberJavaFeatureRunConfigurationProducer
	at io.nimbly.tzatziki.view.features.nodes.GherkinFileNode.getRunConfiguration(GherkinFileNode.kt:32)
	at io.nimbly.tzatziki.view.features.actions.RunTestAction.runFromTreeNode(RunTestAction.kt:59)
	at io.nimbly.tzatziki.view.features.actions.RunTestAction.runFromEditor(RunTestAction.kt:36)
	at io.nimbly.tzatziki.view.features.actions.RunTestAction.actionPerformed(RunTestAction.kt:28)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:381)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:524)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.cucumber.java.run.CucumberJavaFeatureRunConfigurationProducer PluginClassLoader(plugin=PluginDescriptor(name=Cucumber +, id=io.nimbly.tzatziki, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/GoLand2023.3/plugins/plugin-tzatziki, version=17.0.15, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 55 more

```

**Comment by maximehamm** [comment]
Ok... I will fix to remove the exception... but you will not be able to use Gherkin-Breakpoints... because for this feature Cucumber+ plugin needs "Gherkin" plugin... and also "Cucumber for Java" plugin... so far the is no equivalent for GO language... 
Sorry for that
Wait for next release 17.0.16 and please let me know...

**Comment by julalorena** [comment]
Sorry for the late response.
I am using 
IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Runtime version: 17.0.10+1-b1087.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4054M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (233.15026.16)
  CheckStyle-IDEA (5.88.1)
  com.intellij.aqua (233.15026.15)
  com.intellij.spring.batch (233.14015.23)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (233.15026.9)
  cucumber-javascript (233.11799.188)
  org.sonarlint.idea (10.4.1.77998)
Kotlin: 233.15026.9-IJ

**Comment by maximehamm** [comment]
Then I think it should be fixed for you Jululorena (ie it should be fixed for Ultimate). Please confirm.

**Comment by julalorena** [comment]
Yes it is fixed, thank you very much!

**Comment by maximehamm** [comment]
Please share how Cucumber+ is helpfull for you :) 
https://plugins.jetbrains.com/plugin/16289-cucumber-/edit/reviews

**Comment by maximehamm** [comment]
Guess it is fixed...
