### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by s2k** [maximehamm/tzatziki#75]
I'm getting this (warning) in Cucumber+ 17.2.0 with Build #IU-241.14494.240:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.nimbly.tzatziki.actions.TableShiftUpAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.nimbly.tzatziki]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by maximehamm** [comment]
Hum... I will have to remove the support of production 2021.*
It will be done in version 17.2.1
Thank you Stephan
