### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot create extension 

### ISSUE THREAD

**Issue by danny-su** [maximehamm/tzatziki#83]
com.intellij.diagnostic.PluginException: Cannot create extension (class=io.nimbly.tzatziki.TzCucumberJavaRunConfigurationProducer) [Plugin: io.nimbly.tzatziki]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:988)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:73)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:33)
	at com.intellij.openapi.extensions.impl.ExtensionPointImplKt.getOrCreateExtensionInstance(ExtensionPointImpl.kt:1052)
	at com.intellij.openapi.extensions.impl.ExtensionPointImplKt.access$getOrCreateExtensionInstance(ExtensionPointImpl.kt:1)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$iterator$2.advanceToNextNonNull(ExtensionPointImpl.kt:283)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$iterator$2.hasNext(ExtensionPointImpl.kt:265)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe$intellij_platform_extensions(ExtensionProcessingHelper.kt:166)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.kt:66)
	at pro.bashsupport.f_.z(f_.java:183)
	at pro.bashsupport.f_.q(f_.java:157)
	at pro.bashsupport.bw.k(bw.java:44)
	at pro.bashsupport.bw.invoke(bw.java:44)
	at pro.bashsupport.f_.i(f_.java:69)
	at pro.bashsupport.f_.n(f_.java:44)
	at pro.bashsupport.z_.appFrameCreated(z_.java:9)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:664)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy2/jdk.proxy2.$Proxy93.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter$openProjectIfNeeded$isOpenProjectNeeded$1$1.invokeSuspend(IdeStarter.kt:117)
	at com.intellij.idea.IdeStarter$openProjectIfNeeded$isOpenProjectNeeded$1$1.invoke(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$openProjectIfNeeded$isOpenProjectNeeded$1$1.invoke(IdeStarter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
	at com.intellij.idea.IdeStarter$openProjectIfNeeded$isOpenProjectNeeded$1.invokeSuspend(IdeStarter.kt:115)
	at com.intellij.idea.IdeStarter$openProjectIfNeeded$isOpenProjectNeeded$1.invoke(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$openProjectIfNeeded$isOpenProjectNeeded$1.invoke(IdeStarter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded$suspendImpl(IdeStarter.kt:114)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$start$2$openProjectBlock$1.invokeSuspend(IdeStarter.kt:75)
	at com.intellij.idea.IdeStarter$start$2$openProjectBlock$1.invoke(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$start$2$openProjectBlock$1.invoke(IdeStarter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.idea.IdeStarter$start$2.invokeSuspend(IdeStarter.kt:85)
	at com.intellij.idea.IdeStarter$start$2.invoke(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$start$2.invoke(IdeStarter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.idea.IdeStarter.start$suspendImpl(IdeStarter.kt:70)
	at com.intellij.idea.IdeStarter.start(IdeStarter.kt)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$executeApplicationStarter$2.invokeSuspend(ApplicationLoader.kt:395)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$executeApplicationStarter$2.invoke(ApplicationLoader.kt)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$executeApplicationStarter$2.invoke(ApplicationLoader.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader.executeApplicationStarter(ApplicationLoader.kt:394)
	at com.intellij.platform.ide.bootstrap.StartupUtil$startApplication$9.invokeSuspend(main.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class io.nimbly.tzatziki.TzCucumberJavaRunConfigurationProducer (
  error: org/jetbrains/plugins/cucumber/java/run/CucumberJavaScenarioRunConfigurationProducer,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Cucumber +, id=io.nimbly.tzatziki, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.1/plugins/plugin-tzatziki, version=17.4.0, package=null, isBundled=false), packagePrefix=null, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:331)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:178)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1466)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:895)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:20)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
	... 68 more
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/plugins/cucumber/java/run/CucumberJavaScenarioRunConfigurationProducer
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1108)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:291)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:116)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:240)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:190)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:326)
	... 73 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.cucumber.java.run.CucumberJavaScenarioRunConfigurationProducer PluginClassLoader(plugin=PluginDescriptor(name=Cucumber +, id=io.nimbly.tzatziki, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.1/plugins/plugin-tzatziki, version=17.4.0, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 81 more

**Comment by LanceZant** [comment]
I just got the same exception immediately upon post-install restart.  First 3 stack frames appear to be the same, but then the stack trace diverges, probably b/c I'm running the latest IntelliJ Ultimate, 2024.3 (full info at bottom).

Oops, disregard.  When I went to uninstall, I noticed the notice, "Incompatible:  reqires IDE build 242.* or earlier".  Mine is 243.*


IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 12, 2024
Licensed to Charter Communications / Lance Zant
Subscription is active until March 31, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 13.7
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
  editor.minimap.enabled=true
Non-Bundled Plugins:
  com.jetbrains.space (243.21565.122)
  com.intellij.ideolog (243.21565.208)
  com.intellij.guice (243.21565.129)
  com.jetbrains.jax.ws (243.21565.129)
  CheckStyle-IDEA (5.98.0)
  SequenceDiagram (4.0.3)
  gherkin (243.21565.122)
  com.intellij.ml.llm (243.21565.247)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  MavenRunHelper (4.29.0-IJ2022.2)
  com.intellij.bigdatatools.core (243.21565.211)
  com.intellij.bigdatatools.binary.files (243.21565.129)
  com.intellij.bigdatatools.rfs (243.21565.211)
  com.intellij.bigdatatools.metastore.core (243.21565.129)
  com.intellij.bigdatatools.flink (243.21565.129)
  io.nimbly.tzatziki (17.10.0)
  com.github.copilot (1.5.29.7524)
  org.sonarlint.idea (10.12.0.79769)
  com.intellij.bigdatatools.kafka (243.21565.129)
  com.intellij.bigdatatools.spark (243.21566.1)
  com.intellij.bigdatatools.zeppelin (243.21565.129)
  com.intellij.bigdatatools (243.21565.129)
Kotlin: 243.21565.193-IJ
